### ISSUE TITLE
Suggestions for game additions/replacements

### ISSUE THREAD

**Issue by anonCantCode** [Divested-Mobile/FOSS_Apps_List#3]
* [LibreSudoku](https://www.f-droid.org/en/packages/com.kaajjo.libresudoku/) - The best Sudoku app out there IMHO, even if you consider non-FOSS options. Nothing against the the other Sudoku app currently listed, but this is just much better.
* [Puzzles](https://www.f-droid.org/en/packages/name.boyle.chris.sgtpuzzles/) - Classic (but still updated) collection of 40 single player puzzles.
* [Mill](https://www.f-droid.org/en/packages/com.calcitem.sanmill/) - Ancient board game with, IIRC, an original AI opponent implementation.
* [Lexica](https://www.f-droid.org/en/packages/com.serwylo.lexica/) - Word finding puzzle.
* [Lato](https://www.f-droid.org/en/packages/ardash.lato/) - "Alto's Adventure" FOSS clone.
* [2048](https://www.f-droid.org/en/packages/org.andstatus.game2048/) - Again, just much better than the version currently listed. Even has fancy features like auto-solve.
* [Dooz](https://www.f-droid.org/en/packages/io.github.yamin8000.dooz/) - aka Tic Tac Toe.

Related rant: Lichess is amazing for online play (and does work offline to an extent, to be clear) but the other, offline chess app listed is ugly, lacking in basic features such as undo and move history, and its engine is bad to the point of unuseability for those who are even a little good at chess. On top of all this, you can't even resume a game after closing the app. (I realize I come across as a bit harsh but it's hard to rephrase while also elucidating the app's shortcomings.)

Consider replacing it with [DroidFish](https://www.f-droid.org/en/packages/org.petero.droidfish/), which is basically the holy grail of offline chess apps IMHO with a ton of features for both gameplay and analysis. I did not include it in the main list because it does require internet permissions to optionally use self-hosted chess engines.

**Comment by SkewedZeppelin** [comment]
Thank you for this list, I'll try them out soon!
